services:
  - type: web
    name: sprint-poker-backend
    runtime: python
    repo: https://github.com/kathiresh-i2i/sprint-poker.git
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    plan: free
    healthCheckPath: /

  - type: web
    name: sprint-poker-app
    runtime: static
    repo: https://github.com/kathiresh-i2i/sprint-poker.git
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://sprint-poker-backend.onrender.com
      - key: VITE_WS_BASE_URL
        value: wss://sprint-poker-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
